#!/usr/bin/env python3

import os
import py_compile

def main():
  # Get the name of the Python file from the environment variable
  py_file = os.environ["PYFILE"]

  # Set the output filename to be the name of the Python file with a '.pyc' extension
  out_file = py_file + "c"

  # Compile the Python file
  py_compile.compile(py_file, cfile=out_file, doraise=True)

if __name__ == "__main__":
  main()

